### ISSUE TITLE
Aliases not compatible with <$link />

### ISSUE THREAD

**Issue by KalciferKandari** [mklauber/tiddly-aliases#2]
This fix https://github.com/Jermolene/TiddlyWiki5/pull/4552, which was added in TiddlyWiki 5.1.22, introduced a small change to `$:/core/ui/ListItemTemplate`, where `<$link to={{!!title}}><$view field="title"/></$link>` was replaced with `<$link />`. Not sure why, but when aliases is enabled the content between the `a` tags, `<a>what should be here</a>`, does not show up for lists generated with that tiddler.

**Comment by mklauber** [comment]
Hey, so some recent changes have dropped to the LinkWiddget (see here: https://github.com/Jermolene/TiddlyWiki5/issues/3974), and since my plugin overwrites the LinkWidget, it replaces them with the old classic version (plus my changes).  Unfortunately, there's not a good way to do what I need to do in a forward compatible way, so there's always a chance of TW causing breaking changes.  

I'll see about getting this updated to the new LinkWidget code sometime next week.

**Comment by mklauber** [comment]
Sorry for the delay, but I'm pretty sure I've got a fix up now
